version: '3.3'
services:
    db:
        image: mysql:8-debian
        restart: always
        environment:
            MYSQL_DATABASE: 'todoapp'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'todoapp'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'password'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
        # Where our data will be persisted
        volumes:
            - ./dev/data/db:/var/lib/mysql
    backend:
        build: .
        restart: always
        depends_on:
            - db
        ports:
            - '8000:8000'
        env_file:
            -   .env
