version: '3.3'
services:
  backend:
    image: ghcr.io/csse6400/todo-app:latest
    restart: always
    ports:
      - '8000:8000'
    environment:
      APP_KEY: 'base64:8PQEPYGlTm1t3aqWmlAw/ZPwCiIFvdXDBjk3mhsom/A='
      APP_ENV: 'local'
      APP_DEBUG: 'true'
      LOG_LEVEL: 'debug'